baseURL = "http://micz.it/"
languageCode = "en-us"
title = "Mic's"

publishDir = "docs"
theme = "anubis"

googleAnalytics = "UA-3931804-1"
enableRobotsTXT = true

[params]
   customCSS = ["css/micz.css"] # relative path to "static" directory
   Subtitle = "Silence is golden."
   style= "auto"
   #env= "production"