baseURL = "https://micz.it/"
languageCode = "en"
title = "Mic's"

publishDir = "docs"
theme = "anubis"

enableRobotsTXT = true

disableKinds = ["RSS","taxonomy","sitemap"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
   customCSS = ["css/micz.css"] # relative path to "static" directory
   forceCSSReloadID = "20241010"
   Subtitle = "Silence is golden."
   style= "auto"
   env= "production"


[services]
  [services.googleAnalytics]
    ID = "G-14PLEX7LGC"