baseURL = "https://micz.it/"
languageCode = "en"
title = "Mic's"

publishDir = "docs"
theme = "anubis"

enableRobotsTXT = true

disableKinds = ["RSS","taxonomy","sitemap"]
ignoreErrors = ["error-disable-taxonomy"]
ignoreFiles = ["\\.json$"]

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.it]
    languageName = "Italiano"
    weight = 2
  [languages.fr]
    languageName = "Français"
    weight = 3

[params]
   customCSS = ["css/micz.css"] # relative path to "static" directory
   forceCSSReloadID = "20260305"
   Subtitle = "Silence is golden."
   style= "auto"
   env= "production"


[services]
  [services.googleAnalytics]
    ID = "G-14PLEX7LGC"