baseURL = "https://micz.it/"
languageCode = "en"
title = "Mic's"

publishDir = "docs"
theme = "anubis"

#googleAnalytics = "UA-3931804-1"
enableRobotsTXT = true

disableKinds = ["RSS","taxonomy","sitemap"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
   customCSS = ["css/micz.css"] # relative path to "static" directory
   Subtitle = "Silence is golden."
   style= "auto"
   env= "production"
