name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - docs/**

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup GitHub Pages
      - name: Setup Pages
        uses: actions/setup-pages@v3

      # Copy the content of the 'docs' folder to the GitHub Pages artifact directory
      - name: Copy docs to artifact directory
        run: |
          mkdir -p ./github-pages
          cp -r docs/* ./github-pages

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4


